### ISSUE TITLE
Task announcement email lists number of assignments instead of number of tasks?

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#1002]
Not entirely sure. But I just received:

> A new task is now available to you on Daemo. Give feedback on: "Ask Reading Comprehension Questions" 
> $1.00 
> 29 available tasks 
> by mark.whiting 

But there's just one task, and 29 assignments.

**Comment by dmorina** [comment]
i think it's a recent bug, used to show the number of tasks available to you

**Comment by markwhiting** [comment]
I've been seeing this for a few of my past tasks. Not sure how long ago it started.

**Comment by mbernst** [comment]
![download](https://user-images.githubusercontent.com/249285/32623582-85d54016-c53b-11e7-99f5-a5ee29776789.jpeg)

**Comment by markwhiting** [comment]
![Accept](https://media.giphy.com/media/l3vRdCnP428P2TgvS/giphy.gif)

**Comment by mbernst** [comment]
Oddly a propos
