### ISSUE TITLE
Clicking on the discuss link for a task redirects me to the homepage

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#1009]
Video: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/249285/32908871-c18c1444-cab9-11e7-840b-3ae398e4230a.gif)

Going to forum.daemo.org works, so my session's not expired...

**Comment by mbernst** [comment]
Whoops GIF conversion didn't work and is looping all silly, please hold

**Comment by mbernst** [comment]
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/249285/32909087-77d6d55e-caba-11e7-80fb-5298e9a583b2.gif)

Full GIF

**Comment by dmorina** [comment]
SAD
