### ISSUE TITLE
We don't know when workers have previewed tasks.

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/daemo#1012]
Can we add another status event that lets us know when a particular task has been previewed and no further action has been taken? 

One way to do this would just be to add a preview status when the preview loads and then add the in-progress status if they accept the task. This seems nice for analysis, but might be annoying from other perspectives. 

Another option might be to do something with analytics tools but I'm less sure if that will give us granular insights.

**Comment by dmorina** [comment]
1. you preview a project rather than a task (i.e the task is a sample task)
2. we can't add a status, but we can log that data per project
