### ISSUE TITLE
Preview reporting to DB appears to miss some previews

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/daemo#1016]
To reproduce this I was able to view a task ([346](https://www.daemo.org/task-feed/346)) and immediately see that it was previewed, then try the same thing with another task ([333](https://www.daemo.org/task-feed/333)) and see no update in the DB.

**Comment by markwhiting** [comment]
There should be a line for 333 in-between these two.

<img width="606" alt="screen shot 2017-11-24 at 12 09 23 pm" src="https://user-images.githubusercontent.com/673171/33222969-5ad49854-d110-11e7-8c40-65451302ee98.png">

**Comment by dmorina** [comment]
works just fine, maybe you have some cache problems

**Comment by markwhiting** [comment]
Perhaps you're too powerful?
