### ISSUE TITLE
Host images via drag-and-drop

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#1024]
### The problem
I would call this low priority. Right now, tasks can include images that I have hosted, where I give the system the URL to display. It can be inconvenient to go find a place to host every image I want to display in the task.

### The proposal
Ideally, the requester could drag-and-drop an image and we'd host it for them on S3, much like GitHub.

Pros: much easier user experience
Cons: nontrivial amount of engineering work (drag-drop target, uploading). Not clear it's the highest priority.

What are we supposed to do with proposals that are useful, but may not be a priority currently? Like, it's useful to log this somewhere.
- - -
**To break consensus** use [this template](https://gist.githubusercontent.com/markwhiting/ea8875602acd11e79002763735701503/raw/a8da103e23c07b74b4007459170104af04e38a33/break_consensus.md). You may also install this template to your account by following [these instructions](https://help.github.com/articles/creating-a-saved-reply/).

**Comment by markwhiting** [comment]
Our priority model is based on people taking up a proposal. I think basically if nobody takes it up, and nobody beaks consensus, it could just sit in the backlog, similar to how issues do now.

**Comment by mbernst** [comment]
So the proposal would be approved, but would remain in GitHub until someone picks it up?

**Comment by markwhiting** [comment]
My thought was more that proposals without people who are saying they can work on something now are just left in stasis.

**Comment by mbernst** [comment]
Closing as imported to the /collective proposals list. Comment there instead!
