### ISSUE TITLE
Bonus workers in requester settings

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#1025]
### The problem
I had a worker attempt a task but eventually return it without submitting. I'd like to bonus the worker for their effort. But there's no way to do that if they never submitted the task.

### The proposal
I suggest adding the bonus interface to the requester settings dialog, above "Block workers":
<img width="774" alt="screen shot 2017-12-05 at 2 16 04 pm" src="https://user-images.githubusercontent.com/249285/33633901-3bca81e8-d9c7-11e7-8338-1d1a97e112f4.png">

Or at the very least, add a link to the bonus interface from there.

- - -

**To break consensus** use [this template](https://gist.githubusercontent.com/markwhiting/ea8875602acd11e79002763735701503/raw/a8da103e23c07b74b4007459170104af04e38a33/break_consensus.md). You may also install this template to your account by following [these instructions](https://help.github.com/articles/creating-a-saved-reply/).

**Comment by markwhiting** [comment]
This has been imported to /collective in crowdresearch/collective#7.

**Comment by mbernst** [comment]
Closing as imported to the /collective proposals list. Comment there instead!
