### ISSUE TITLE
Make tasks available to the requester immediately

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#1027]
### The problem
A worker is reporting a problem with my task, but it hasn't boomerang'ed down to me yet, so I can't test the task myself.

### The proposal
Can we default a requester to a 3.0 for themselves?

Is this a bug? Or a proposal?

- - -
#### Do not remove  
**To break consensus** use [this template](https://gist.githubusercontent.com/markwhiting/ea8875602acd11e79002763735701503/raw/a8da103e23c07b74b4007459170104af04e38a33/break_consensus.md). You may also install this template to your account by following [these instructions](https://help.github.com/articles/creating-a-saved-reply/).

**Comment by markwhiting** [comment]
🐛
