### ISSUE TITLE
Let a worker reference a specific task when they ask questions on the forum

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#1028]
### The problem
A worker is trying to reference "some of these" tasks to give feedback. This can be difficult to establish common ground: which tasks specifically have the issues? Can I see them? It feels like it's working around a lack of ability to comment on a specific task. Example: https://forum.daemo.org/t/count-the-number-of-statistical-tests-in-a-research-paper/322/10

### The proposal
I propose we find a way to let a worker ask a question about a specific `task`, which gets linked on the forum. That way the requester can look.

Open question: would workers use this? The worker thinks so: "Yes - I think that would be helpful to call out a specific task so that on my side and yours we know specifically what we’re talking about."

I think this may already be possible, like by linking to the specific task: https://www.daemo.org/task/61141/

The question is whether we want to make this even easier.

Right now if the task URL would work and allow the requester to see the task that the worker is calling out, then we're good.

- - -
**To break consensus** use [this template](https://gist.githubusercontent.com/markwhiting/ea8875602acd11e79002763735701503/raw/a8da103e23c07b74b4007459170104af04e38a33/break_consensus.md). You may also install this template to your account by following [these instructions](https://help.github.com/articles/creating-a-saved-reply/).

**Comment by dmorina** [comment]
fyi the issue template has been updated earlier today which makes "the proposal" section conditional

**Comment by markwhiting** [comment]
The page where workers' submissions are visible might be a good candidate for this. e.g.: https://www.daemo.org/task-preview/18117 (this is a submission I did to test returns)

Somewhat critically, it appears there's no security on those. As in, anyone with a daemo account can look at any prior task submission. So, we might not want workers to share those on the forum.

**Comment by dmorina** [comment]
@markwhiting you reminded me of something, can you write in the issue template that security issues should be reported via support@daemo.org instead of here (it's a standard procedure)

**Comment by markwhiting** [comment]
This has been imported to /collective in https://github.com/crowdresearch/collective/issues/6.

**Comment by mbernst** [comment]
Closing as imported to the /collective proposals list. Comment there instead!
