### ISSUE TITLE
@mbernst should be part of all the technical quality review and technical operations teams

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/daemo#1034]
Since the start of this project @mbernst has unofficially taken these rolls. He is technically adept, is heavily involved with day to day operations, and has a strong track record of contributing an enormous amount of time to this project.

---
**Use comments to share your response** or use emoji 👍 to show your support. **To officially join in**, comment `I will help.` **To break consensus**, comment using [this template](https://gist.githubusercontent.com/markwhiting/ea8875602acd11e79002763735701503/raw/269916fe3c151cee51726f4f7f0488bec3010836/break_consensus.md). To find out more about this process, read the [how-to](https://gist.github.com/markwhiting/1fc8529fd074c12231c553936beec668).

**Comment by iceLearn** [comment]
I will support this proposal.

**Comment by markwhiting** [comment]
Duplicate of https://github.com/crowdresearch/collective/issues/1
