### ISSUE TITLE
Mobile: requester name appears twice in the task feed

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#1035]
The requester name is so nice, we list it twice:
![image](https://user-images.githubusercontent.com/249285/34056797-564bbb94-e189-11e7-82f0-dbd236dec920.png)

Screenshot taken on iPhone 7 Plus --- a.k.a. "iPhone-not-notched"

I am assuming that the intended behavior was to show the name in the new row, hiding it in the upper right.

---
**Use comments to share your response** or use emoji 👍 to show your support. **To officially join in**, comment `I will help.` **To break consensus**, comment using [this template](https://gist.githubusercontent.com/markwhiting/ea8875602acd11e79002763735701503/raw/269916fe3c151cee51726f4f7f0488bec3010836/break_consensus.md). To find out more about this process, read the [how-to](https://gist.github.com/markwhiting/1fc8529fd074c12231c553936beec668).

**Comment by dmorina** [comment]
yeah, that was the intended behavior, will fix the directives
