### ISSUE TITLE
Bug in the signup flow leaves new workers with accounts they can't use

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/daemo#1038]
People trying to signup to Daemo as workers are confused by the lack of any explanation about why they can't select worker or both. We had previously had an error message that displayed a link to fill out the form to join our waiting list, but since changing the signup flow to allow requesters, that is no longer visible. Furthermore, this happens rather late in the process, by the time this selection is made the user has already clicked an authentication email and filled in a range of details. 

Here's what new registrants see: 
![dae fail](https://user-images.githubusercontent.com/673171/34284999-0f07a7fa-e68b-11e7-9080-9909c5d1f8fa.JPG)

I'm not sure what the best solution would be, perhaps to ask what kind of participant they want to be on the initial signup page, and to provide the previous message if they select worker at that time?

---
**Use comments to share your response** or use emoji 👍 to show your support. **To officially join in**, comment `I will help.` **To break consensus**, comment using [this template](https://gist.githubusercontent.com/markwhiting/ea8875602acd11e79002763735701503/raw/269916fe3c151cee51726f4f7f0488bec3010836/break_consensus.md). To find out more about this process, read the [how-to](https://gist.github.com/markwhiting/1fc8529fd074c12231c553936beec668).

**Comment by iceLearn** [comment]
Good point @markwhiting , I just tried to register with my other mail and found that if we enter the date by typing  it does not allow. See the underlined red 
![image](https://user-images.githubusercontent.com/12571844/34289814-4301dcd0-e71a-11e7-8297-158c18de3a03.png)

Clicking the date calendar start with 2017 which need my be go back to 30 odd years;) thats not good UX. 
![image](https://user-images.githubusercontent.com/12571844/34289919-c33b30c2-e71a-11e7-9764-dec8e2b7c355.png)

After everything filled, then comes the issue raised my @markwhiting. 
We should upfront let know the registrations either we are not yet ready to for worker or allow registration for a waiting list in google form. 
I see this as important issue and need a bug fixing immediately with some ideas. 
- What do we want to do - take the worker registrations?
- If we want workers -->fixing the links, if not--> re-direct them to waiting list of explain the situation upfront

**Comment by dmorina** [comment]
sorry about that, not sure how the text from the email didn't make it to this page, it was definitely intended to
