### ISSUE TITLE
The IRB being served is inconsistent with what we have on file

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/daemo#1041]
The IRB at https://daemo.org/auth/irb is out of date with the one we have on file with Stanford. These are intended to remain in sync with each other so this is an inconsistency or bug. 

I've submitted a PR (https://github.com/crowdresearch/daemo/pull/1040) updating the IRB to the latest version and fixing this bug.

---
**Use comments to share your response** or use emoji 👍 to show your support. **To officially join in**, comment `I will help.` **To break consensus**, comment using [this template](https://gist.githubusercontent.com/markwhiting/ea8875602acd11e79002763735701503/raw/269916fe3c151cee51726f4f7f0488bec3010836/break_consensus.md). To find out more about this process, read the [how-to](https://gist.github.com/markwhiting/1fc8529fd074c12231c553936beec668).

**Comment by dmorina** [comment]
don't forget the `closes #ISSUE_NR` to close these automatically
