### ISSUE TITLE
Emails for requesters and workers

### ISSUE THREAD

**Issue by shirishgoyal** [crowdresearch/daemo#831]
Requester
- [ ] new joiner
- [ ] post 1st project
- [ ] once all responses are received
- [ ] completion of 1st project

Worker
- [x] on publish of new batch of tasks
- [ ] approval and payment
- [x] rejection of task - reason

[Email Content](https://docs.google.com/document/d/1p6YGc1cHVoaQ-41ueSuhaBlEEQd4oXVULS7Lr3NkGg8/edit?usp=sharing)

**Comment by qwertyone** [comment]
Requester

- first returned task from workers for revision (?)
- first revised task re-submission (?)

**Comment by dmorina** [comment]
break it into smaller issues and reopen when we need it
