### ISSUE TITLE
Interface should show what a project's Boomerang status is

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#874]
Probably on the review page, or maybe on the Requester Status page, we should have a UI element that tells the requester what level of people currently have access. Ideally also some information about when the last time we gated more people in was, and when we might do it again.

**Comment by mbernst** [comment]
![pl9bscewtf2zphlpwzmxog_thumb_688c](https://user-images.githubusercontent.com/249285/27878771-2c234804-6174-11e7-8b89-04719f46a8f0.jpg)

**Comment by mbernst** [comment]
http://www.spiceforms.com/blog/wp-content/uploads/2014/05/CSS3-BreadCrumb-Navigation-with-Hover.png

**Comment by abhay-venkatesh** [comment]
where exactly on the page to put the boomerang status bar? I was thinking above the responses, and the bar can be responsive to fill the page's width too.

**Comment by dmorina** [comment]
just prepare a directive which accepts an array of such "checkpoints" and also the current value and we'll place it wherever when ready

**Comment by abhay-venkatesh** [comment]
I kinda made something with just a custom HTML + CSS solution.  Is that fine or should I adapt it into a directive?

**Comment by abhay-venkatesh** [comment]
<img width="1428" alt="screen shot 2017-07-12 at 11 10 37 pm" src="https://user-images.githubusercontent.com/14362082/28152846-675011b2-6757-11e7-84ae-5c5f55496cf9.png">

Still have to style it exactly to the Daemo color scheme but this is not a directive yet. Simple HTML <div> with class tag and CSS>

**Comment by dmorina** [comment]
i guess it's fine

**Comment by abhay-venkatesh** [comment]
I was planning to add tooltips to the elements too, so the user understands what exactly the boomerang status means, any suggestions for what they should say?

**Comment by abhay-venkatesh** [comment]
ok current logic is:

priority if min_rating > 2
normal if min_rating >= 1.99 AND <= 2
late workers if min_rating < 1.99

is that correct @dmorina ?

If yes, then I have everything working. A concern would be with responsiveness to smaller screen sizes (but the overall UI does not seem to accommodate that anyway...)

**Comment by abhay-venkatesh** [comment]
<img width="1420" alt="screen shot 2017-07-13 at 11 08 14 pm" src="https://user-images.githubusercontent.com/14362082/28200305-2c3ff816-6820-11e7-995d-0c2a2ea701d7.png">

**Comment by abhay-venkatesh** [comment]
I tried to "materialize" it as much as possible. Let me know if I should change something, otherwise ready to PR.

**Comment by dmorina** [comment]
you could change the border radius a bit 2px maybe or 4px, check what looks better and yeah just go ahead with the PR

**Comment by dmorina** [comment]
the logic is correct

**Comment by dmorina** [comment]
what's the status on this?

**Comment by abhay-venkatesh** [comment]
@dmorina I've been discussing this on the #daemo-launch feed. I want to discuss combining this status notification with the table buttons.
