### ISSUE TITLE
Add academic account information in the account creation context

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/daemo#881]
Currently users might create an account and then later realize they needed to create it with their academic email address.

**Comment by dmorina** [comment]
Can you draft a sentence that we could add to the signup form for this?

**Comment by markwhiting** [comment]
Sure how about: 
> Sign up with an academic (.edu) or non-profit (.org) email address for discounts.

**Comment by mbernst** [comment]
And link "discounts" to the page describing the policy

**Comment by markwhiting** [comment]
Thats currently a page that is only visible to members.

@mbernst, do you think we should make the forum publicly visible? I know thats possible, and might support our claims of friendliness.

**Comment by mbernst** [comment]
I'm in principle ok with this. Any concern about workers not wanting their comments public? Seems reasonable to me esp since Turkopticon etc are public

**Comment by markwhiting** [comment]
Yea, that was my thought too. I've made an issue for this, #884, where we can work out any details.
