### ISSUE TITLE
Create an academic account deadline for students 

### ISSUE THREAD

**Issue by qwertyone** [crowdresearch/daemo#883]
This is to maintain integrity of the academic community due to the large turn over of graduates and professors who might quit the university setting.

**Comment by dmorina** [comment]
what does this mean?

**Comment by dmorina** [comment]
.edu accounts are accepted as non-profit so the discounts will be applied, closing this

**Comment by qwertyone** [comment]
I just read this. This means that there would be a platform policy that matches normal cycles for a person in a school. For example, a graduate researcher with the .edu account would  have 2 to 3 years of discounted use. Thereafter, if the .edu is not maintained, they go to the normal use fees.
