### ISSUE TITLE
Transition forum to public content

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/daemo#884]
In the same way many other crowd work forums are public, this would help people outside our community understand our culture.

It would also allow for public linking of documents stored within the forum, as was mentioned in #881.

**Comment by dmorina** [comment]
moving this to the forum repo https://github.com/crowdresearch/daemo-forum/issues

all issues related to the forum should be moved there -> parts of the issues that need to be completed on the forum

**Comment by shirishgoyal** [comment]
All forum related issues should be posted in this repo only as we are not maintaining separate codebase for forum. If needed, we will make changes via plugins to keep auto-upgrades manageable.
