### ISSUE TITLE
Display time estimate

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#887]
Because people can only check out one task per project, submit_time-accept_time actually seems to be a reasonable estimate sometimes. Let's see if we can include it in the task feed and on the task page. We need to think about how to design it.

**Comment by markwhiting** [comment]
I know some workers have been interested in a personalized timer. I wonder if its good to do both, to some extent, once people have started working on a task. For example:
> **Average Duration**
> You: **3:42** Others: **3:57**

The key point often discussed with this is effective hourly wage, but I'm not sure if that would be better directly reported or not. For example: 

> Takes about **4 minutes**. Effective wage:
> You: **$11.12/h** Others: $10.53/h

**Comment by mbernst** [comment]
If exact wages are weird to calculate, we had also talked about flagging tasks that are below CA min wage. So they're red or something. Maybe we don't full confidence that we can exactly estimate your exact wage, but we can pretty well know if you're not getting paid enough.

**Comment by markwhiting** [comment]
Several workers said they're doing that calculation them selves. So perhaps we give them some kind of guess that we think is a safe minimum, so they don't feel the need to spend time checking it, and so they usually earn a little more than we reported.

It certainly seems much better to be under than over.

**Comment by dmorina** [comment]
i just went with whatever @markwhiting proposed above, looks fine
