### ISSUE TITLE
Mouse cursor should become a grabby hand on the move-item knob in the task design interface

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#891]
At the top of this item:
<img width="744" alt="screen shot 2017-07-10 at 3 25 13 pm" src="https://user-images.githubusercontent.com/249285/28042845-fbe95c28-6583-11e7-9115-2713f991959a.png">

I go from an arrow to a cursor (like for typing) --- but it should be a hand for grabbing that nub to move the item.

**Comment by dmorina** [comment]
#webkitProblems

**Comment by mbernst** [comment]
So broken in both Safari and Chrome?

**Comment by dmorina** [comment]
yep, already fixed, used `cursor: -webkit-grab;` to fix that

**Comment by mbernst** [comment]
Oh! Didn't see the commit closing this. Sorry.

**Comment by dmorina** [comment]
https://media.giphy.com/media/l3vR3EssQ5ALagr7y/giphy.gif
