### ISSUE TITLE
Worker downloadable work history

### ISSUE THREAD

**Issue by qwertyone** [crowdresearch/daemo#895]
https://slack-files.com/T03R8AQ66-F67EE3JMT-71d07c354c

Workers expressed a requirement of a fair platform is the ability to view and download work samples that are both machine readable and human readable. 

As a counter balance, requesters should be able to control the privacy of all their own task submissions or anonymized sections of work. This might even have timing controls of when work is visible after a period of time.

In case where it is not possible, task metadata might be made visible on a work history widget on the profile page for public review, if desired by the worker.

**Comment by mbernst** [comment]
Do we have a long-range tag or something that we can come back to once things start to stand on their own?

**Comment by dmorina** [comment]
no, usually it's the backlog but if it grows with stuff that we might not do then it's hard to keep track.. so usually we just keep them closed until we decide that it should be included in the next release or so. i.e reopen when it becomes relevant

**Comment by dmorina** [comment]
we'll come back to this one when we decide that we actually wanna do it
