### ISSUE TITLE
Forum daemon should post in threads when the requester updates task info

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#900]
e.g., changing the title, price, number of tasks

Ideally we have it just revise its original post. Otherwise, let's have it just append a new post to the thread that notes the change.

**Comment by mbernst** [comment]
Woooo #900!

**Comment by dmorina** [comment]
goal is to go over 9000 tho

**Comment by shirishgoyal** [comment]
@dmorina you are inching towards a wrong goal :) Having that many tasks posted per month makes sense

**Comment by shirishgoyal** [comment]
Original post is revised when requester updates project info
