### ISSUE TITLE
More informative page titles

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#901]
I don't think our templates currently let us set the page title. But then our demos end up with this:
<img width="490" alt="screen shot 2017-07-13 at 11 47 13 am" src="https://user-images.githubusercontent.com/249285/28182456-1a765cba-67c1-11e7-8061-bf2dae324c6b.png">

I should have added a more informative title in case someone linked to it.

**Comment by dmorina** [comment]
i added these to the routes, although it won't help for the case mentioned above because we are using angularjs the title won't be rendering in such preview mode, unless the js is fully loaded
