### ISSUE TITLE
Tasks with price ranges appear somewhat unclearly

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/daemo#903]
It seems like price ranges wrap, and are positioned relatively low in the task feed item, making it somewhat unclear what the numbers indicate. Here's an example:

<img width="130" alt="screen shot 2017-07-16 at 10 20 54 pm" src="https://user-images.githubusercontent.com/673171/28253791-225ccf98-6a75-11e7-8b6b-44c53e237e65.png">

This also makes it unclear what the main price number is indicating. Is it the average? How would I know as a worker?

One solution would be to explicitly state that the price is variable and then its bounds:

> **Variable**
> $22.87 to $54.48

Another would be to list the low end as the price, and then mention the high end separately:
> **At least $22.87**
> up to $54.48

**Comment by dmorina** [comment]
people understand that a `-` represents a range min to max 
i will add a tooltip for the median

**Comment by dmorina** [comment]
tooltip added

**Comment by markwhiting** [comment]
Yes, but being broken over two lines and being positioned right justified makes it less clear.

**Comment by dmorina** [comment]
<img width="525" alt="screen shot 2017-07-17 at 11 04 53 am" src="https://user-images.githubusercontent.com/2858281/28282577-ca2c5b8e-6adf-11e7-9351-2b84bf68c706.png">


not sure why it breaks for you

**Comment by markwhiting** [comment]
OK. Looks like it's a browser thing. It is not broken in Chrome, and is in Safari.

**Comment by dmorina** [comment]
ah ok, will check Safari then

**Comment by mbernst** [comment]
<img width="783" alt="screen shot 2017-07-17 at 11 11 58 am" src="https://user-images.githubusercontent.com/249285/28282854-c86860a8-6ae0-11e7-96dc-62f52bb17625.png">

Mine (Safari)
