### ISSUE TITLE
Durim is appearing in my task feed

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#904]
<img width="529" alt="screen shot 2017-07-17 at 2 55 09 pm" src="https://user-images.githubusercontent.com/249285/28291601-fcca21c8-6aff-11e7-879e-eae1a684b0e6.png">

**Comment by markwhiting** [comment]
Is that an issue? Sounds like a feature.

**Comment by dmorina** [comment]
definitely a feature
