### ISSUE TITLE
Pausing a project from the Requester Status returns a cryptic error

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#909]
<img width="305" alt="screen shot 2017-07-19 at 10 04 36 am" src="https://user-images.githubusercontent.com/249285/28379768-b8b081b0-6c69-11e7-92bd-a2b9c70b2745.png">

...and I don't think it paused.

**Comment by dmorina** [comment]
are you trying to resume a paused and edited project by any chance?
because it won't let you do that from requester status as designed

**Comment by dmorina** [comment]
i don't seem to be able to reproduce it

**Comment by dmorina** [comment]
re-open if it happens again it was an internal server 500
