### ISSUE TITLE
Markdown code blocks don't wrap or respect max width

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#910]
<img width="1101" alt="screen shot 2017-07-19 at 10 18 13 am" src="https://user-images.githubusercontent.com/249285/28380301-b531bad4-6c6b-11e7-88aa-a892034d2eb2.png">

**Comment by dmorina** [comment]
sad times

**Comment by dmorina** [comment]
what is this view? preview?

**Comment by mbernst** [comment]
Yes, preview

**Comment by dmorina** [comment]
<img width="1440" alt="screen shot 2017-07-19 at 11 37 24 am" src="https://user-images.githubusercontent.com/2858281/28383642-b0875bd2-6c76-11e7-80d6-851b338cc4fb.png">
