### ISSUE TITLE
Make instruction blocks collapsible, and save the state for each project

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#911]
I bet it would save workers a lot of scrolling over time.

**Comment by dmorina** [comment]
for each project for each block?

**Comment by mbernst** [comment]
Yeah. So if I collapse a given instruction block for the project, it stays collapsed as I continue to work on tasks.

**Comment by dmorina** [comment]
it can be done in the front end but to store these in the backend the change is YUGE and probably not worth it, i.e we only store the results of the input components

**Comment by dmorina** [comment]
closing, not feasible to implement it as originally described, also workers don't seem to have issues with it 

reopen if it's really an issue, and after some major modifications of this issue
