### ISSUE TITLE
Number of open tasks reports total, but this isn't the same as the number of open to the worker

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#912]
For example I have a task with 99 rows * 2 assignments. The task feed says:
<img width="74" alt="screen shot 2017-07-19 at 11 04 21 am" src="https://user-images.githubusercontent.com/249285/28382168-1a60ba62-6c72-11e7-8225-49ba5570eb72.png">

But the worker can only actually do 99 tasks, so it seems disingenuous for the task feed to say 198 open. Like AMT, it should report the number of tasks open to the worker --- in this case, the number of tasks with at least one replication left available.

**Comment by dmorina** [comment]
but still there are 198 open from requester's point of view

**Comment by mbernst** [comment]
OH my mistake, I thought I was looking at the task feed

**Comment by dmorina** [comment]
FraudNews
