### ISSUE TITLE
Better handling of revisions with project IDs

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#915]
When I edit a project, it's odd that the ID changes. For example, when I embed the task, we shouldn't have to get a new project ID when I update the project. I'm not against the system transparently forwarding on to the most recent revision if it gets an old one. But better would be something that's a static project identifier.

**Comment by dmorina** [comment]
alright, now you can use whatever id you like or the Project Key renamed to `Project Identifier`

**Comment by dmorina** [comment]
i.e if a project has 3 revisions say id = {1, 2, 3} and it's project key is `kQm0M` then using any of these 4 will preview id=3 the latest revision as requested

**Comment by mbernst** [comment]
Ok!
