### ISSUE TITLE
Report aggregate demographics in results page

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#926]
I think that this will be an important way to humanize the workers to the requesters. By surfacing that your workers are, e.g., in the US, aged 20-30, education level XXX, I think it would start overturning misconceptions that many requesters have about who crowd workers are.

**Comment by mbernst** [comment]
Though counterargument:
```
This does not mean that requesters should know individual workers’ first and last names, email addresses, geographical locations, educational backgrounds, or work histories — in fact, giving requesters such information might give them more power than they already have over workers. Rather, it means that the design and messaging of the platform should incentivize and prime requesters to realistically consider workers’ abilities, needs, contexts, and limitations while designing and reviewing tasks.
```

https://medium.com/@silberman/design-notes-for-a-future-crowd-work-market-2d7557105805

**Comment by dmorina** [comment]
didn't we already decide on this and also implemented it a while back?
However, it will only show if you have more than 10 workers working for you else you can easily figure out who is who .. so that won't happen until we get more workers

**Comment by mbernst** [comment]
Can we try reducing that to 3 workers for now, just so we can get a better sense of what it feels like?

**Comment by dmorina** [comment]
done!
