### ISSUE TITLE
Task # in results table doesn't match the # in CSV download

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#929]
In my CSV ZIP I see a number four thousand something:
<img width="133" alt="screen shot 2017-07-24 at 10 59 47 am" src="https://user-images.githubusercontent.com/249285/28537301-3799ae5e-705f-11e7-9a9e-ddd714886a2a.png">

But in the result table the task number is in the ten-thousands:
<img width="326" alt="screen shot 2017-07-24 at 11 00 06 am" src="https://user-images.githubusercontent.com/249285/28537316-4378397a-705f-11e7-9431-ca6126a3eb20.png">

Shouldn't the task number (in either case) be indexed from 1 for each project?

**Comment by mbernst** [comment]
(Though at the very least it would be nice to be able to align which upload is from which submission)

What if the file name format were taskid-workername-filename

**Comment by dmorina** [comment]
one of them is the assignment id and the other is task id which is not unique so that cannot be the same, i can add file name as a column to the csv
