### ISSUE TITLE
Daemo forum favicon looks stretched out

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#938]
<img width="137" alt="screen shot 2017-07-27 at 8 57 13 am" src="https://user-images.githubusercontent.com/249285/28679941-9ad997a8-72a9-11e7-9442-9a2157b5d2fa.png">

Something something Trump comment

**Comment by shirishgoyal** [comment]
![image](https://user-images.githubusercontent.com/315012/28681301-e43a1036-72ad-11e7-9bce-048ca03de82d.png)
Check if it looks fine now

**Comment by mbernst** [comment]
works
