### ISSUE TITLE
High-five

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#940]
Bear with me. In the FeedMe system (http://people.csail.mit.edu/msbernst/papers/feedme-chi2010.pdf) we found that a simple "One-Click Thanks" feature had huge takeup, and generally very pro-social outcomes.

I think we can use this in Daemo too. Let a requester send a high-five or similar to a worker for a job well done. (We can use this as a foot-in-the-door for sending bonuses, for example.) Likewise let a worker thank a requester if they paid quickly.

We could design it into the result page.

**Comment by dmorina** [comment]
@abhay-venkatesh what's the status of this?

**Comment by abhay-venkatesh** [comment]
@abhay-venkatesh I have implemented the backend stuff needed. Need to finalize what design we need.

**Comment by abhay-venkatesh** [comment]
I've implemented the front-end design as well after getting feedback from @markwhiting

**Comment by dmorina** [comment]
this has been sitting here for more than a month, what's the status here? else we'll just close and move on :D

**Comment by dmorina** [comment]
alrighty then, reopen if it ever becomes relevant again :)
