### ISSUE TITLE
Font sizes in task creation interface don't match the sizes when rendered

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#945]
This is most obvious in the instructions block, where the default font size is big and bold, but it renders as a more normal, lighter-weight font. But I think it occurs across lots of the blocks, and it's inconsistent what things will render like.

Here's in authoring:
<img width="737" alt="screen shot 2017-08-04 at 10 57 23 am" src="https://user-images.githubusercontent.com/249285/28980718-c2070706-7903-11e7-9e92-f05b7abac333.png">

Here's in preview:
<img width="757" alt="screen shot 2017-08-04 at 10 57 30 am" src="https://user-images.githubusercontent.com/249285/28980721-c557cd46-7903-11e7-8e5e-8e40199260a5.png">

**Comment by dmorina** [comment]
umm that's what preview is for? i.e i see your point but they are entirely different components so they don't have to match ..

questions are bold which is fine, instructions should not be as they are long text (paragraphs) and they can use MarkDown to bold stuff if they want meaning we can remove "bold" font-weight from the Instructions input field
