### ISSUE TITLE
Make non-auth'ed webpages have reasonable metadata for Slack unfurling etc

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#949]
The fastest solution might be via meta tags:
https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

**Comment by dmorina** [comment]
Unfurling (terrible name btw) will not work with angular js templating to my knowledge (previews never load js only meta tags), if you wanna do that then you can make these pages django templates but they won't work with angularjs as they do now after that

**Comment by mbernst** [comment]
Why does it work with page titles, then? (Or it wouldn't work with a static indexing?)

**Comment by dmorina** [comment]
closing, not possible using ng templates
