### ISSUE TITLE
Send an email on project completion

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#951]
Re: @dmetaxak's comment

**Comment by dmorina** [comment]
Email body and subject?

**Comment by mbernst** [comment]
SUBJECT: Work complete: {{projectname}}

It's ready — Daemo workers have submitted all tasks for your project, {{projectname}}. Now you can <a href project review page>go review their work and approve it.</a> As a reminder, each submission is automatically approved and paid after two business days if you don't take any action. Before then, you can ask workers to revise their submission if you'd like them to iterate based on your feedback.
