### ISSUE TITLE
Minor CSS issue: can see table scrolling from above the worker header

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#953]
You can see the text peeking out above the "priority" button for example:
<img width="1300" alt="screen shot 2017-08-09 at 9 42 09 pm" src="https://user-images.githubusercontent.com/249285/29154763-a9474df6-7d4b-11e7-87dd-a4d268721ee1.png">

Project 174

**Comment by mbernst** [comment]
(Chrome)

**Comment by dmorina** [comment]
seems to be chrome only

**Comment by dmorina** [comment]
no idea what's going on with this, chrome + sticky + something about a parent = this
