### ISSUE TITLE
CSV is missing a column

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#954]
Check out project 175. Revision 3 CSV is missing the "year" column. It renders in the HTML table though.
[When_did_this_researcher_get_their_PhD-.zip](https://github.com/crowdresearch/daemo/files/1215750/When_did_this_researcher_get_their_PhD-.zip)

**Comment by dmorina** [comment]
retest please.. should work

**Comment by mbernst** [comment]
[When_did_this_researcher_get_their_PhD-.zip](https://github.com/crowdresearch/daemo/files/1216086/When_did_this_researcher_get_their_PhD-.zip)

Still no year column

**Comment by dmorina** [comment]
i guess the server thinks it optional to include this field too :D

**Comment by dmorina** [comment]
alright, should really work now, if not https://media0.giphy.com/media/Rz4rvx1DApTEs/giphy.gif :D
