### ISSUE TITLE
Allow posthoc payment adjustment

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#960]
Report the median hourly, and give the requester the ability to posthoc up workers' payments to a different wage rate.

Even if workers don't reject the task, but its pay rate is too low, we could even consider forcing this if it goes below CA minimum wage.

**Comment by dmorina** [comment]
sorry, can you elaborate on this? i understand the "Report the median hourly" part

**Comment by markwhiting** [comment]
I believe this was the median hourly wage earned by workers when doing that task.

**Comment by dmorina** [comment]
the median time calculation in the most projects seems to be very unreliable (except the tasks that take few seconds and can be done in batches), that makes it impossible to report anything useful to the users .. this ticket may become relevant if we design something like a worker self report (maybe something simple "is this paying enough")
