### ISSUE TITLE
Review page doesn't tell me when I fail prototype task

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#963]
I had two workers both reject the prototype task but the feedback in the review page says I can launch:
<img width="677" alt="screen shot 2017-09-06 at 7 43 18 pm" src="https://user-images.githubusercontent.com/249285/30171232-5f2ea4d2-93bf-11e7-8647-e0a1a70e4150.png">

Shouldn’t it tell me to revise my task and relaunch the prototype task?

**Comment by dmorina** [comment]
is it that the link to Edit Project is missing?

**Comment by dmorina** [comment]
n/a anymore until redesign
