### ISSUE TITLE
Review page: possible to align the text under the table with the text in the table?

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#964]
<img width="76" alt="screen shot 2017-09-06 at 7 43 27 pm" src="https://user-images.githubusercontent.com/249285/30171258-73bc7686-93bf-11e7-8cd3-fb6c17f45548.png">

**Comment by dmorina** [comment]
<img width="1008" alt="screen shot 2017-09-07 at 2 57 21 pm" src="https://user-images.githubusercontent.com/2858281/30187058-ef1e2b40-93dc-11e7-9161-21b6e0444eac.png">

The text above the card defines the left starting point, if you put that text in the same worker card then sure otherwise no

**Comment by dmorina** [comment]
two options here: move it inside the card or leave it as it is, @mbernst what do you prefer?

**Comment by dmorina** [comment]
oh and your browser sucks, Mark just pointed that your looks different from the screenshot i posted :D

**Comment by dmorina** [comment]
alignment fixed on Chrome, it's Safari that has to suffer the consequences unfortunately but it is what it is since more people use Chrome
