### ISSUE TITLE
Possible layout bug in the task authoring environment

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#965]
<img width="461" alt="screen shot 2017-09-06 at 7 45 19 pm" src="https://user-images.githubusercontent.com/249285/30171267-7d3987f8-93bf-11e7-9333-4dcad92c59d1.png">

I got this by going in to edit after my prototype task failed

**Comment by dmorina** [comment]
broken since we made changes to make it responsive, fixing
