### ISSUE TITLE
Can still hack around a launch after prototype task fails

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#966]
I just went in and changed the number of assignments after my prototype task failed, and it let me. Doesn’t that let me go around the prototype task requirement and re-increase my number of workers?
<img width="358" alt="screen shot 2017-09-06 at 7 54 35 pm" src="https://user-images.githubusercontent.com/249285/30171294-9792ddde-93bf-11e7-953d-673ad1b8f468.png">

I would assume the general flow is:
- I launch PTask
- PTask fails
- I get an email. When I open the task results, the message tells me that I need to revise my task and re-launch the prototype before it can go live to the full marketplace
- When I go to the task design page, it tells me to revise the task based on the feedback (repeating the feedback) and then re-launch the prototype. During this period the # assignments and # tasks. still says what it said before. I can change them, but this just gets fed back into the PTask algorithm when I relaunch.
- When I relaunch, it recomputes the PTask quantities and launches the prototype task just like it did the first time.

**Comment by dmorina** [comment]
it does let you publish even without changing anything, i don't think we wanna go into figuring out "what is a significant change" in order to be able to tell if they did the right thing so it's up to the requester.

**Comment by dmorina** [comment]
there's no way to detect that the feedback has been addressed so why bother, if you say well check if template has changed they can just go and add a space somewhere and they could bypass that :D

**Comment by dmorina** [comment]
will revisit once redesigned, if it becomes relevant
