### ISSUE TITLE
Probably wontfix: offline resources

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#967]
When I’m doing stuff offline, the cloudflare / google maps APIs still make this take a while to load the page. I’m guessing the answer is no, but anyway to circumvent that?

**Comment by mbernst** [comment]
(To be clear, I mean when I'm running Daemo on localhost while not connected)

**Comment by dmorina** [comment]
yeah nah, javascript or anything else cannot detect that you are offline and the script tags will attempt to load anyway

**Comment by dmorina** [comment]
closing, see comments above
