### ISSUE TITLE
Price calculator

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#971]
Feedback was: "One thing off the bat that would be super useful is a task pricing calculator. If the ideal is to use CA minimum wage then it would be cool if you could input how long you think the task will take (and any other criteria that should be taken into account) and have it suggest a task price."

The obvious question is whether the current calculator is discoverable enough.

**Comment by dmorina** [comment]
Feedback from?
And if anyone has an algorithm to calculate task price correctly  I would be very interested 😅

**Comment by mbernst** [comment]
We have what they want: they wanted something where they could estimate time and then we'd tell them a price. We do the opposite. My first impression is that what we have is fine. But it's clear that they didn't find it very obvious. Just noting the feedback for now, we can de-/re-prioritize.

**Comment by dmorina** [comment]
sorry, what is the problem that we are trying to solve?
did any of our requesters who have posted task underpay workers (below min wage)?

**Comment by mbernst** [comment]
The problem was that the requester didn't find our calculator. I suspect there's not much to do here yet — let's keep the issue open for a little bit to see if any other requesters have the problem.

**Comment by markwhiting** [comment]
Yes. everyone I've onboard was confused by our calculator as is. I'm doing 2 more on Monday, I'll try to see what they think would work better.

**Comment by mbernst** [comment]
Can you say more about the nature of the confusion?

**Comment by markwhiting** [comment]
Sure. For example, in the B12 call, they didn't get "assignments per task" initially, they also didn't get what "To achieve California Minimum Wage, workers need to be able to finish this task in 0 seconds." meant. Then when they started editing it they were a little surprised how the numbers went together, as in it seemed to interact in an unintuitive way for them. 

Granted, this is live on a call, so it may have been easier to ask me what something meant than to think about it or play with it enough to work it out. 

Re the "0 seconds" thing, we could not show that until values have been entered. 

Also, it seems like nobody really knows what California minimum wage is, so perhaps we could mention that in the helper text.

**Comment by markwhiting** [comment]
Just a thought for a next action here: Replace the text before a price has been entered to say something slightly differently, so it makes more sense.

> We recommend pricing tasks to achieve [California Minimum Wage](http://www.minimum-wage.us/state.php/?state=California) of $10.50 per hour.

As a sub note, I think it would also be nice to link to [California Minimum Wage](http://www.minimum-wage.us/state.php/?state=California), or to quote it.
