### ISSUE TITLE
Requesters need some on-boarding for prototype tasks

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/daemo#978]
This would appear immediately after launching a task, as a kind of next screen that all requesters are forced into, unless they opt out with the switch on this page.
![onboarding r2](https://user-images.githubusercontent.com/673171/31111568-cfcb2cd4-a7c3-11e7-9961-5cd0033abfa8.png)
This is intended to use the standard design library in implementation, though it may deviate slightly in this visualization.

The text in the box is: 
> **Your project has launched as a prototype**
> All Daemo projects launch as prototypes first, which ensures they're ready for primetime. Workers  leave feedback on the project and try a few tasks. If they feel that it's ready, the rest of the project will launch automatically.
> Your prototype will consist of 20 of the 200 tasks, and 1 of the 4 workers.

**Comment by markwhiting** [comment]
@dmorina are there any details you may need for this that are currently missing?

**Comment by dmorina** [comment]
reopen when PT becomes relevant again (ie design is finalized)
