### ISSUE TITLE
Autopopulate new requesters with some starter funds

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#984]
We had chatted about using some of the Sloan money to autopopulate new requester accounts with $5 or something like that so they could test out the platform. I think the question is, is it possible to avoid sybil attacks where someone creates a bunch of different accounts? Would Stripe catch that? Or can we otherwise allow one account per credit card, or something like that?

**Comment by dmorina** [comment]
regardless of profit/nonprofit status right? @mbernst

**Comment by dmorina** [comment]
reopen if we should only do for non profit accounts, current implementation is for all
