### ISSUE TITLE
Requester name position breaks taskfeed if the task name is too long

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/daemo#990]
<img width="274" alt="screen shot 2017-10-17 at 11 51 46 am" src="https://user-images.githubusercontent.com/673171/31683367-b1372c7c-b331-11e7-850c-585e1f590fdb.png">

This is in Safari 11 on macOS 10.13

**Comment by markwhiting** [comment]
I'm still seeing it, I think.

<img width="214" alt="screen shot 2017-10-17 at 6 17 27 pm" src="https://user-images.githubusercontent.com/673171/31696633-7f711c9e-b367-11e7-955b-568d36ec07eb.png">

**Comment by dmorina** [comment]
Cache maybe?

**Comment by markwhiting** [comment]
I did that a few times, and it didn't work initially but is now. Meta cache...
